[package]
name = "galactica"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Simple implementation of RDBMS"
rust-version = "1.92.0"

[dependencies]

[dev-dependencies]
